global:
  deploymentMode: null
  deploymentStrategy: Recreate
  imageRegistry: ""
  imagePullSecrets: []

affinity: {}

platform:
  logging:
    aspect:
      enabled: false

api:
  basePath: /v1alpha/applications

automountServiceAccountToken: true

clusterName: ""

container:
  extraEnvVars: ""
  extraVolumeMounts: ""
  extraVolumes: ""
  livenessProbe: |
    httpGet:
      path: /actuator/health/liveness
      port: {{ .Values.container.port }}
      httpHeaders:
        - name: X-B3-Sampled
          value: "0"
    failureThreshold: 1
    initialDelaySeconds: 180
    periodSeconds: 20
    successThreshold: 1
    timeoutSeconds: 5
  port: 8080
  readinessProbe: |
    httpGet:
      path: /actuator/health/readiness
      port: {{ .Values.container.port }}
      httpHeaders:
        - name: X-B3-Sampled
          value: "0"
    failureThreshold: 30
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  resources:
    limits: {}
    requests: {}
  securityContext:
    runAsUser: 1001
  startupProbe: ""

dbchecker:
  enabled: true
  image:
    pullPolicy: IfNotPresent
    repository: busybox
    tag: 1.32
  securityContext:
    allowPrivilegeEscalation: false
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000

dnsPolicy: ClusterFirst

dnsWildcard: ""

extraInitContainers: ""

extraTrafficExcludeOutboundPorts: "6379,26379,26380,27017"

fullnameOverride: ""

image:
  pullPolicy: IfNotPresent
  pullSecrets:
    - regcred
  repository: application-external-context
  tag: latest

ingress:
  enabled: true
  ingressClassName: ""

istio:
  sidecar:
    enabled: true
    requestsLimitsEnabled: true
    resources:
      limits: {}
      requests: {}

keycloak:
  certificatesEndpoint: /protocol/openid-connect/certs
  url: ""
  realms:
    mygov: mygov-biz-portal
    admin: admin

lifecycleHooks: {}

mongodb:
  autoIndexCreation: true
  database: "application_external_context"
  # If name not <.Values.clusterName>-< .Release.Namespace >-< .Values.postgres.database >
  databaseOverride: ""
  integrationSecretName: "mongodb-connection-details"
  appSecretName: "mongodb-app-secrets"
  replicaset:
    enabled: false
  ssl:
    enabled: false
  collections:
    applicationSteps: application_steps
    applicationVars: application_vars

externalContext:
  ttl: 30d

nameOverride: ""

nodeSelector: {}

podAnnotations: {}

podSecurityContext:
  fsGroup: 1001

replicas: 1

schedulerName: default-scheduler

service:
  nodePort: ""
  port: 8080
  type: ClusterIP

serviceAccount:
  create: true
  name: application-external-context

terminationGracePeriodSeconds: 30

tolerations: []
