apiVersion: v1
kind: Service
metadata:
  name: {{ include "application-external-context.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "application-external-context.labels" . | nindent 4 }}
spec:
  ports:
    - name: api
      {{- if .Values.service.type }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      {{- end }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
  selector:
    {{- include "application-external-context.selectorLabels" . | nindent 4 }}
  type: {{ default "ClusterIP" (.Values.service.type | quote) }}
